testing

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -183,14 +183,17 @@ jobs:
 
     
     dev-integracion-testing:
-            name: Dev Integration Testing
-            needs: dev-deploy
-            runs-on: ubuntu-latest
-            steps:
-              - name: Test URL Output using CURL and JQ
-                env:
-                  URL: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL}}
-                run: |
-                  echo $URL
-                  echo "------------------------"
-                  curl https://$URL/live -s -k | jq -r .status | grep -i live
+      name: Dev Integration Testing
+      needs: dev-deploy
+      runs-on: ubuntu-latest
+      steps:
+      - name: Test URL Output using CURL and JQ
+        env:
+         URL: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL}}
+        run: |
+          echo "Testing URL: $URL"
+          echo "------------------------"
+          curl -v https://$URL/live -s -k || echo "CURL failed but continuing"
+          curl https://$URL/live -s -k | jq -r .status | grep -i live || echo "Live check failed"
+
+                  
